/****** Object:  StoredProcedure [dbo].[wbl_tapa_farm]    Script Date: 10/06/2007 12:55:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[wbl_tapa_farm]
	
@FARMIN INT

AS
BEGIN
	
SELECT DISTINCT TAPA.IDC_TAPA AS LLAVEMR, TAPA.NOMBRE_TAPA AS DESCRIPCIONMR, TAPA.ID_TAPA AS ID_TAPA 
FROM TAPA, PRODUCTO_FARM 
WHERE PRODUCTO_FARM.ID_FARM=@FARMIN 
AND PRODUCTO_FARM.ID_TAPA=TAPA.ID_TAPA
AND TAPA.DISPONIBLE = 1

END
