/****** Object:  StoredProcedure [dbo].[wbl_caja_farm]    Script Date: 10/06/2007 12:28:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[wbl_caja_farm]

@FARMIN INT

AS
BEGIN

SELECT DISTINCT TIPO_CAJA.IDC_TIPO_CAJA, IDC_TIPO_CAJA, CAJA.IDC_CAJA, CAJA.NOMBRE_CAJA AS NOMBRETICA, 
PRODUCTO_FARM.ID_TIPO_FLOR AS LLAVETIF, CAJA.ID_CAJA AS ID_CAJA 
FROM CAJA, PRODUCTO_FARM, TIPO_CAJA 
WHERE CAJA.ID_CAJA=PRODUCTO_FARM.ID_CAJA AND TIPO_CAJA.ID_TIPO_CAJA=CAJA.ID_TIPO_CAJA 
AND PRODUCTO_FARM.ID_FARM = @FARMIN 
ORDER BY NOMBRETICA ASC

END
