/****** Object:  StoredProcedure [dbo].[wbl_tipo_flor_farm]    Script Date: 10/06/2007 12:56:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[wbl_tipo_flor_farm]

@FARMIN INT

AS
BEGIN

SELECT DISTINCT TIPO_FLOR.IDC_TIPO_FLOR AS LLAVETIF, 
TIPO_FLOR.NOMBRE_TIPO_FLOR AS NOMBRETIF, 
TIPO_FLOR.ID_TIPO_FLOR AS ID_TIPO 
FROM PRODUCTO_FARM, 
TIPO_FLOR 
WHERE PRODUCTO_FARM.ID_TIPO_FLOR = TIPO_FLOR.ID_TIPO_FLOR AND 
PRODUCTO_FARM.ID_FARM = @FARMIN 
AND TIPO_FLOR.DISPONIBLE = 1
ORDER BY NOMBRETIF ASC

END
